stages:
  - build
  - test

build:
  stage: build
  script:
    - cd Aplication
    - ./gradlew build -x test
    - ./gradlew.bat --stop

test:
  stage: test
  script:
    - cd Aplication
    - ./gradlew test
    - ./gradlew.bat --stop
  artifacts:
    paths:
      - Aplication\build\reports\tests\test
